# This rule is not used by the project projekt itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over monitoring.bi-ws2025.de.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: projekt
    app.kubernetes.io/managed-by: kustomize
  name: observation-admin-role
rules:
- apiGroups:
  - monitoring.bi-ws2025.de
  resources:
  - observations
  verbs:
  - '*'
- apiGroups:
  - monitoring.bi-ws2025.de
  resources:
  - observations/status
  verbs:
  - get
